### ISSUE TITLE
Error in config/parser.php for Twig

### ISSUE THREAD

**Issue by billmn** [fuel/parser#1]
To avoid problems with Twig Autoloader, the name of the directory in app/vendor must be "Twig" ( not lower or upper )

So in the package there's an error in "config/parser.php", change the current configuration with :

```
'View_Twig' => array(
    'include'     => APPPATH.'vendor'.DS.'Twig'.DS.'Autoloader.php',
),
```

And it works fine

**Comment by jschreuder** [comment]
Will be fixed by your pull-request once it's ready.
