### ISSUE TITLE
Smarty Template Inheritance and Includes

### ISSUE THREAD

**Issue by TreeNode** [fuel/parser#18]
Including files or extending files require full path to templates directory:

For example: 

{include '..\fuel\app\views\my_template.smarty'}

{extends file='..\fuel\app\views\header.smarty'}

**Comment by jschreuder** [comment]
Is this an issue? What do you expect? What do you currently get?

Be a bit more descriptive.

**Comment by TreeNode** [comment]
Was expecting to be able to just use

{include 'my_template.smarty'}

{extends file='header.smarty'}

And know to look into my views folder.

Would this be a parser config item?

Thank you

**Comment by iquito** [comment]
My pull request https://github.com/fuel/parser/pull/21 solved this by setting the template directory for Smarty.

**Comment by TreeNode** [comment]
That fixed the issue I was experiencing. Thanks iquito!
