### ISSUE TITLE
Get parser driver instance in controller

### ISSUE THREAD

**Issue by billmn** [fuel/parser#19]
Look at : http://www.fuelphp.com/forums/topics/view/4059

**Comment by jschreuder** [comment]
Already possible as @Wanwizard pointed out using the parser method.

Either request it on a specific driver class or on a view object:

```
View_Smarty::parser();
$view->parser();
```

**Comment by billmn** [comment]
No ...
if you make a static call in a controller like \Parser\View_Smarty::parser() ( is the same for twig and other drivers ) you haven't execute a View::factory() method and template library class isn't included.

We can add a "include_once" on a _init() function on every driver class, like

<pre>
public static function _init()
{
    include_once \Config::get('parser.View_Smarty.include');
}
...
</pre>


I've just prepared all drivers with this method ... if you agree I can send a pull request

**Comment by jschreuder** [comment]
Adding the inclusion to _init() is a good idea, I would prefer it to still support multiple files even though we know the number of files per driver. That keeps the code nice and consistent:

```
// Include necessary files
foreach ((array) \Config::get('parser.'.$class.'.include', array()) as $include)
{
    require_once $include;
}
```

**Comment by billmn** [comment]
Ok Jelmer!
In _init() we also have to add a parent::_init() to not override auto_encode config check.
