### ISSUE TITLE
Overriding View causes Parser to not load

### ISSUE THREAD

**Issue by ShonM** [fuel/parser#28]
The solution, I found, was to make sure your extended View was still in the \Fuel\Core namespace.

@dhorrigan and I already chatted about this in IRC. I'm sure he's aware of the issue and its fix, if needed.

**Comment by jschreuder** [comment]
This is not a bug, if you extend View from Fuel\Core\View the Parser won't load, unless you use it directly from Parser\View. If you extend Fuel\Core you get Fuel\Core, if you want Parser\View you extend Parser\View.
