### ISSUE TITLE
Smarty - Setting Cache or Compile ID

### ISSUE THREAD

**Issue by TreeNode** [fuel/parser#33]
Unable to set a cache_id or compile_id in a fetch call. 

For more info:
http://www.smarty.net/docsv2/en/caching.multiple.caches.tpl
http://www.fuelphp.com/forums/topics/view/5195#5263

**Comment by WanWizard** [comment]
There's more wrong here.

The Smarty view class uses fetch() to fetch the smarty template, passing the template data as the second parameter. That doesn't work in Smarty, you have to call assign() on the Smarty object to assign variables to the template, then call fetch().

**Comment by WanWizard** [comment]
Implementing extra fetch parameters is not that easy, as it would interfere with the way the View class is working.

For custom solutions, like passing the cache_id, either do it like you do now, or extend the View class and overload the process_file method.
