### ISSUE TITLE
View's Forge Function doesn't work like Core View Forge Function

### ISSUE THREAD

**Issue by dmyers** [fuel/parser#37]
Something I noticed and I was wondering your guys thoughts on was that the Parser's View::Forge() function doesn't work the same as Core View::Forge() function.

Basically you can could store an instance of the View::forge() in say your controller and not pass any template file name or data for the template and later do it, this is useful for the flow of your application IMO, but with Parser's View::forge() it is optional as a null, but doesn't ignore empty files like the Core View::forge(). Confusing to explain, but maybe someone will understand.

Example:

``` php
public $view;

public function before()
{
    $this->view = View::forge();
}

public function after($response)
{
   return $request->body($this->view);
}

public function test_action()
{
   $this->view->set_filename('path/to/test');
   $this->view->variable = 'test';
}
```

I think the way to improve the Parser's View class is to change it from overriding the forge() and factory() functions and to actually override the __construct() and set_filename() instead, but I could be wrong. Looking for help. :)

**Comment by jschreuder** [comment]
Yes, you are wrong, it's not as simple as that. :-p

While `View::forge()` in the core is just a nice alternative to `new View()`, in the Parser package it does a lot more: it decides which type of View driver it needs to load. This is based on the file extension (as documented), but if there's no file extension it can't make the decission.

I'm open to any solution you might come up with, but as it's undocumented usage I don't consider this a bug. At the most it's a limitation of the Parser package that warrants additional documentation.

**Comment by dmyers** [comment]
Oh okay yeah you are right it appears I was able to just do new View_Twig and still use the parsing. Thanks.
