### ISSUE TITLE
Parser Forge to default to Core View Extension

### ISSUE THREAD

**Issue by dmyers** [fuel/parser#41]
There is a protected variable on the \Fuel\Core\View called "extension" which when set, sets the default. It would be nice if the Parser View would default to that if no extension is detected when using the pathinfo($file).

So instead of:

``` php
$extension  = pathinfo($file, PATHINFO_EXTENSION);
```

It would be something like:

``` php
$extension  = pathinfo($file, PATHINFO_EXTENSION);

if (empty($extension)) {
   $extension = $this->extension;
}
```

What do you guys think?

**Comment by frankdejonge** [comment]
I think it's a good idea. Implementing it now.

**Comment by frankdejonge** [comment]
Wait a second...

**Comment by frankdejonge** [comment]
Although the way it's done is a bit of a cheat, when no extension is provided, the called class is the class that will be returned (through config get default), allowing View_Haml::forge to return a Haml view when no extension is provided, which is what you'd want. When we implement the fallback to $this->extension this functionality will disappear. Aka "not what we want".
