### ISSUE TITLE
SimpleTags throws error when trying to parse arrays

### ISSUE THREAD

**Issue by calvinfroedge** [fuel/parser#5]
Tries to parse array as string and fails.

**Comment by jschreuder** [comment]
Always, and I really mean _always_, give the exact full error message. If possible a screenshot with backtrace, filename & line nrs. There is no other way we can every help you out if you don't.

**Comment by calvinfroedge** [comment]
Here is the error:

Notice!

ErrorException [ Notice ]: Array to string conversion

PKGPATH/parser/vendor/simpletags.php @ line 198:

197:    {
198:    $orig_content = str_replace($tag['marker'], $return_data, $orig_content);
199:    unset($parsed_tags[$key]);

It's an error in my view.  Here is what I am trying to parse (other views in my template.stags):

http://screencast.com/t/GPgGjwuIfWfP

http://screencast.com/t/rOh7BpNgZ

http://screencast.com/t/3XLwnlic

**Comment by calvinfroedge** [comment]
Note that the error occurs even if i comment out everything but the logo getting passed to the views.  The error occurs for each secondary view I am trying to include.

**Comment by jschreuder** [comment]
@dhorrigan could you check this out? I get how SimpleTags works, but as it's your code you'll probably figure it out a lot quicker...

**Comment by jschreuder** [comment]
We've decided to move to Mustache as the default driver. Don't think Dan wants to support SimpleTags anymore so I suggest you move to that or try to fix problems with it yourself. In either case this is a problem with SimpleTags and not with the package thus should be reported here: https://bitbucket.org/dhorrigan/simpletags/issues
