### ISSUE TITLE
MtHaml support

### ISSUE THREAD

**Issue by ronan-gloo** [fuel/parser#59]
I've wrote a parser in order to integrate this project: https://github.com/arnaud-lb/MtHaml 
Haml-Twig is supported through the shipped Twig parser.

Let me know if you're insterested, i'll send a pull request.

Cheers.

**Comment by WanWizard** [comment]
Always interested in new functionality.

We're in a feature freeze at the moment, pending the release of 1.5. So if you can wait a week or so, and then send a PR on 1.6/develop?

**Comment by ronan-gloo** [comment]
Ok, no problem !

**Comment by WanWizard** [comment]
If you come around to looking at this, know that we're moving to Composer at the moment. There is a composer package available for mthaml, so the parser driver should use that.
