### ISSUE TITLE
Load module view with hardcoding

### ISSUE THREAD

**Issue by billmn** [fuel/parser#7]
Parser cannot found view with module view hardcode like View::factory('module::view_name');

I've tried to modify parser view class changing $file with basename() but if I try to load normal view I obtain a fatal error. 

For details on tris issue see : http://fuelphp.com/forums/topics/view/2277

How can we do??

**Comment by WanWizard** [comment]
I can't reproduce this error.

Module view loading is supported through View::find_file(), which is utilized by the parser as well, and which works for me without problems.
