### ISSUE TITLE
Default include paths

### ISSUE THREAD

**Issue by chrisharrison** [fuel/parser#70]
The online docs for 1.6 (http://fuelphp.com/docs/packages/parser/intro.html) explain that if you don't want to change the "config they [template drivers] are expected in app/vendor/{Lib_name}".

It took me a while to figure out that recently the 'include' paths for some of the drivers have been removed or commented out. I was trying to get Twig to work so I placed the lib in app/vendor/Twig but Fuel couldn't find the Twig_Autoloader class.

After some investigating I copied the 'include' config item for 'View_Twig' in the config/parser.php from an earlier version of Fuel so that it reads:
APPPATH.'vendor'.DS.'Twig'.DS.'Autoloader.php'

Suddenly, everything works.

Is there a reason why the default include path has been removed but there is no mention of it in the docs?

**Comment by WanWizard** [comment]
I'll have to check with @FrenkyNet, but I think that it was changed to allow the Parser to work with the Composer versions of these template engines. So as of 1.6 you should use composer to install them, and not install them by hand. 

This indeed has not been updated in the documentation so that needs to be fixed.

**Comment by chrisharrison** [comment]
OK that makes a lot sense. But yeah if the docs mentioned that the whole system will be perfect.

On a personal note please keep up the good work on FuelPHP. A lot of people are talking about Laravel now. I checked it out but I prefer Fuel. I really hope you guys keep it up to date with active development. If I see anything where I can contribute I will. Thanks.

**Comment by WanWizard** [comment]
We're working very hard on 2.0 at the moment (join #fuelphp-status on IRC if you want to see the activity). Most of the core is already up and running, but there's still a lot of work. It's going to be more awesome, while retaining the simplicity of 1.x!

**Comment by WanWizard** [comment]
Docs updated. https://github.com/fuel/docs/commit/9120910b9eb3f3ccbf3b2c1090199a6ec0f50c86
