### ISSUE TITLE
Missing dump() function for twig parser

### ISSUE THREAD

**Issue by spaced-out-mvc** [fuel/parser#83]
I spent an hour or more trying to get the twig debug() function to work.
I read lots of documentations and all pointed to settings debug=true

This didnt work of course. However after manually tracing through the code i found the problem
The dump function is not included in the fuel twig extensions list.

Inside this file
/fuel/packages/parser/classes/twig/fuel/extension.php

You need to add this line inside getFunctions()
'dump' => new Twig_Function_Function('Debug::dump')

I think the dump() function is the most important function it is required for developers i think.

Previously fuelphp supported this function i think there must have been a recent upgrade which has lost this function from the listing.

I would be good if someone could revise the current list, or at least add the above line to future distributions as it is impossible to find it documented online otherwise.

unless you read this of course... lol

Thanks
Daniel

**Comment by spaced-out-mvc** [comment]
now twig templates i can use {{ dump(var) }} as normal
matching the twig documentation

**Comment by emlynwest** [comment]
I am not aware of this function being supported in any version of this package (Do you have the right repo, this is v2 fuel, not v1) but should be easy enough to add.

**Comment by emlynwest** [comment]
My mistake, thought this was another repo. Just ignore the above.

**Comment by spaced-out-mvc** [comment]
This is on the latest Fuelphp v1.7.2 
I think last summer it worked fine on which ever version was available then
it maybe a case of a conflict within the code somewhere else maybe if the file has not been changed
however by adding the line above fixes the issue

It simply adds the dump() function to the fuelphp extension bridge for twig

**Comment by spaced-out-mvc** [comment]
i have been using it all day since and it works 100% perfect
