### ISSUE TITLE
Fatal Error on clean install

### ISSUE THREAD

**Issue by billmn** [fuel/parser#9]
With a clean installation of Fuel RC3 and latest version of parser in "develop" branch, obtain :

"Fatal error: Exception thrown without a stack frame in Unknown on line 0 "

I think that problem is on line 28 ( $file = ... ) in parser/classes/view.php

**Comment by billmn** [comment]
After the fix the error is the same ...
With last WanWizard commit it works : 
https://github.com/fuel/parser/commit/72015cea7985e2ad8ec5730fb865907d4854b1e5

Please don't hate me! :-)

**Comment by jschreuder** [comment]
If you're still getting the same error you should reopen the issue.

And WanWizard's commit was a very Q&D fix, not a worthwhile solution. This should work and does work in my current setup, can you track down where the error occurs for you? There's probably still something off with the filepath, though I don't get why it would work for me but not for you. So echo'ing the filepath and seeing what's wrong with it would probably be a good way. Also I would need to know a lot more about your current setup (which driver are you using + code examples).

**Comment by billmn** [comment]
Sorry but I've tried to click on "Reopen" but Github gived me "You don't have permission to reopen ..."

I don't user any driver ... with a fresh Fuel install there's the default View::factory('welcome/index'); call in controller/welcome.php.

If you try to add extension it works : View::factory('welcome/index.php');
I've only downloaded Fuel RC3, lastest Parser version and added the package to always_load.

In parser/classes/view.php I've changed factory function with :

public static function factory($file = null, array $data = null, $auto_encode = null)
{
    $extension  = pathinfo($file, PATHINFO_EXTENSION);
    $class      = \Config::get('parser.extensions.'.$extension, get_called_class());
    //$file       = substr($file, 0, (-strlen($extension) - 1));

```
print_r(pathinfo($file));
echo "<br />".$file."<br />";
echo substr($file, 0, (-strlen($extension) - 1))."<br />";
exit();

...
```

and the result is :
Array ( [dirname] => welcome [basename] => index [filename] => index )
welcome/index
welcome/inde

**Comment by jschreuder** [comment]
Ok, sorry - I thought users could reopen as well. It's right to work like this though.

But there you got it, the problem is that it doesn't work without an extension. I'll fix this.
