### ISSUE TITLE
View_Markdown

### ISSUE THREAD

**Issue by stvowi** [fuel/parser#95]
There is a false path definition in the config.php for the parser who lead to compile errors if you use makdown files as template file (e.g. View::forge('xyz.md')).

```
'View_Markdown' => array(
    // 'include'     => \Package::exists('parser').'vendor'.DS.'markdown'.DS.'markdown.php', FALSE!!!
	'include'     => \Package::exists('parser').'classes'.DS.'view'.DS.'markdown.php',  //CORRECT
	'auto_encode' => true,
	'allow_php'   => true,
),
```

**Comment by WanWizard** [comment]
The entire line should be removed.

It's original intention was to include the Markdown class file, but since we've switched to the Composer version of Markdown (https://github.com/fuel/parser/commit/4ba6f6c011262a5d32ce69c2ff8a88c5ec71b44d) it is no longer needed.
